### ISSUE TITLE
pool-count is fixed

### ISSUE THREAD

**Issue by dhunteroy** [ikelaiah/threadpool-fp#1]
could you add functions:
self-thread-count   Automatic increase and decrease

**Comment by ikelaiah** [comment]
Hi @dhunteroy , thanks for your interest in the lib. 
The fixed number of thread / processor count was in place because I didn't know a good algorithm to handle this.

Anyhow, the good news is; this is on the way.

**Comment by ikelaiah** [comment]
Closed - not an issue.
